version: "3.8"

services:
  # Node.js backend service
  project-backend:
    build: .
    ports:
      - "8000:8000"
    container_name: express-container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - backend-network
    env_file:
      - .env # Loads all variables from .env
    environment:
      # Optional: override or set defaults here if needed
      PORT: ${PORT}
      ORIGIN_FRONTEND: ${ORIGIN_FRONTEND}
      ORIGIN_ADMIN: ${ORIGIN_ADMIN}
      ORIGIN_FRONTEND_WWW: ${ORIGIN_FRONTEND_WWW}
      SALT: ${SALT}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SRC: ${SMTP_SRC}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_APIKEY: ${CLOUDINARY_APIKEY}
      CLOUDINARY_APISECRET: ${CLOUDINARY_APISECRET}
      RAZORPAY_API_KEY: ${RAZORPAY_API_KEY}
      RAZORPAY_API_SECRET: ${RAZORPAY_API_SECRET}
      GOOGLE_RECAPTCHA_SECRET_KEY: ${GOOGLE_RECAPTCHA_SECRET_KEY}

  db:
    image: postgres:17
    container_name: my_project
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080" # Access Adminer at http://localhost:8080
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
